version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: om30app
    container_name: containerom30-app
    restart: unless-stopped
    working_dir: /app
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8088:8000"
    depends_on:
      - db
    networks:
      - challangeom30net

  db:
    image: postgres:14.7
    container_name: contanerom30-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data/littleoak
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - challangeom30net

networks:
  challangeom30net:
    driver: bridge
