version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}

    db:
        image: postgres:latest
        container_name: db
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./data:/var/lib/postgresql/data

    web:
        image: nginx:latest
        container_name: web
        ports:
            - "8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
        depends_on:
            - app

